param(
    [string]$PublicIP = "",
    [string]$SeedHost = "chepay-node1.duckdns.org",
    [int]$P2PPort = 28333,
    [int]$RPCPort = 28332
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$duckDnsCompose = Join-Path $repoRoot "docker\\duckdns\\compose.yaml"
$duckDnsEnv = Join-Path $repoRoot "docker\\duckdns\\.env"

if (!(Test-Path $duckDnsCompose)) { throw "Missing $duckDnsCompose" }
if (!(Test-Path $duckDnsEnv)) { throw "Missing $duckDnsEnv" }

Write-Host "Starting DuckDNS updater container..."
docker compose -f $duckDnsCompose --env-file $duckDnsEnv up -d

Write-Host "Waiting briefly for DNS updater startup..."
Start-Sleep -Seconds 3

$appData = [Environment]::GetFolderPath("ApplicationData")
$chepayDir = Join-Path $appData "ChePay"
New-Item -ItemType Directory -Force $chepayDir | Out-Null

$confPath = Join-Path $chepayDir "chepay.conf"
$conf = @"
# Autogenerated bootstrap config for ChePay network bring-up.
# Generated by scripts/start-network.ps1

[main]
server=1
listen=1
dns=1
port=$P2PPort
rpcport=$RPCPort
addnode=${SeedHost}:$P2PPort
"@

if ($PublicIP) {
    $conf += "`nexternalip=${PublicIP}:$P2PPort`n"
}
$conf | Set-Content $confPath

Write-Host "Wrote config to $confPath"

# Basic DNS resolution check
try {
    $resolved = Resolve-DnsName $SeedHost -ErrorAction Stop | Where-Object { $_.Type -eq 'A' } | Select-Object -First 1
    if ($resolved) {
        Write-Host "Resolved $SeedHost -> $($resolved.IPAddress)"
    } else {
        Write-Warning "No A record currently returned for $SeedHost"
    }
} catch {
    Write-Warning "DNS resolve failed for ${SeedHost}: $($_.Exception.Message)"
}

# If GUI binary exists, launch it; otherwise give next-step path.
$qtCandidate = Get-ChildItem -Path $repoRoot -Recurse -Filter "chepay-qt.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
if ($qtCandidate) {
    Write-Host "Launching GUI: $($qtCandidate.FullName)"
    Start-Process -FilePath $qtCandidate.FullName
} else {
    Write-Warning "chepay-qt.exe not found yet. Build GUI, then run this script again to auto-launch."
}

Write-Host "Network bootstrap prep complete."

