param(
    [string]$PublicIP = "",
    [string]$SeedHost = "chepay-node1.duckdns.org",
    [int]$P2PPort = 28333,
    [int]$RPCPort = 28332,
    [switch]$EnableLocalMining = $true,
    [int]$MineEverySeconds = 45
)

$ErrorActionPreference = "Stop"

function Find-Binary {
    param(
        [string]$RepoRoot,
        [string[]]$Names
    )

    $preferred = @(
        (Join-Path $RepoRoot "build_msvc\\bitcoin-qt\\x64\\Release"),
        (Join-Path $RepoRoot "build_msvc\\bitcoin-cli\\x64\\Release"),
        (Join-Path $RepoRoot "build_msvc\\x64\\Release")
    )

    foreach ($dir in $preferred) {
        foreach ($name in $Names) {
            $candidate = Join-Path $dir $name
            if (Test-Path $candidate) {
                return $candidate
            }
        }
    }

    foreach ($name in $Names) {
        $found = Get-ChildItem -Path $RepoRoot -Recurse -Filter $name -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($found) {
            return $found.FullName
        }
    }

    return $null
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$duckDnsCompose = Join-Path $repoRoot "docker\\duckdns\\compose.yaml"
$duckDnsEnv = Join-Path $repoRoot "docker\\duckdns\\.env"

if ((Test-Path $duckDnsCompose) -and (Test-Path $duckDnsEnv)) {
    Write-Host "Starting DuckDNS updater container..."
    docker compose -f $duckDnsCompose --env-file $duckDnsEnv up -d
    Write-Host "Waiting briefly for DNS updater startup..."
    Start-Sleep -Seconds 3
} else {
    Write-Warning "DuckDNS compose or env file missing, skipping container startup."
}

$appData = [Environment]::GetFolderPath("ApplicationData")
$chepayDir = Join-Path $appData "ChePay"
New-Item -ItemType Directory -Force $chepayDir | Out-Null

$confPath = Join-Path $chepayDir "chepay.conf"
$confLines = @(
    "# Autogenerated bootstrap config for ChePay network bring-up."
    "# Generated by scripts/start-network.ps1"
    ""
    "[main]"
    "server=1"
    "listen=1"
    "dns=1"
    "port=$P2PPort"
    "rpcport=$RPCPort"
    "addnode=${SeedHost}:$P2PPort"
)

if (![string]::IsNullOrWhiteSpace($PublicIP)) {
    $confLines += "externalip=${PublicIP}:$P2PPort"
}

$confLines -join "`r`n" | Set-Content $confPath
Write-Host "Wrote config to $confPath"

try {
    $resolved = Resolve-DnsName $SeedHost -ErrorAction Stop | Where-Object { $_.Type -eq "A" } | Select-Object -First 1
    if ($resolved) {
        Write-Host "Resolved $SeedHost -> $($resolved.IPAddress)"
    } else {
        Write-Warning "No A record currently returned for $SeedHost"
    }
} catch {
    Write-Warning "DNS resolve failed for ${SeedHost}: $($_.Exception.Message)"
}

$qtPath = Find-Binary -RepoRoot $repoRoot -Names @("bitcoin-qt.exe", "chepay-qt.exe")
$cliPath = Find-Binary -RepoRoot $repoRoot -Names @("bitcoin-cli.exe", "chepay-cli.exe")

if ($qtPath) {
    Write-Host "Launching GUI: $qtPath"
    Start-Process -FilePath $qtPath
} else {
    Write-Warning "GUI binary not found. Build first, then rerun this script."
}

if ($EnableLocalMining -and $cliPath) {
    $minerScript = Join-Path $repoRoot "scripts\\auto-mine-local.ps1"
    if (Test-Path $minerScript) {
        Write-Host "Starting local auto-miner helper with $cliPath"
        Start-Process -WindowStyle Hidden -FilePath "powershell.exe" -ArgumentList @(
            "-ExecutionPolicy", "Bypass",
            "-File", "`"$minerScript`"",
            "-CliPath", "`"$cliPath`"",
            "-RpcPort", "$RPCPort",
            "-IntervalSeconds", "$MineEverySeconds"
        )
    } else {
        Write-Warning "Auto-miner script missing: $minerScript"
    }
} elseif ($EnableLocalMining) {
    Write-Warning "CLI binary not found, cannot start auto-miner."
}

Write-Host "Network bootstrap prep complete."
